In [1]:
import pandas as pd 
import numpy as np

In [2]:
def calculate_distance(lon1, lat1, lon2, lat2):
    # 1. Convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    # 2. Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    # 3. Radius of earth in kilometers is 6371
    km = 6371 * c
    return km

In [3]:
df = pd.read_csv(r"D:\Repos\ML-Practice\ML\Uber\Dataset\uber.csv")

In [4]:
df.head(20)

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5
5,44470845,2011-02-12 02:27:09.0000006,4.9,2011-02-12 02:27:09 UTC,-73.969019,40.755910,-73.969019,40.755910,1
6,48725865,2014-10-12 07:04:00.0000002,24.5,2014-10-12 07:04:00 UTC,-73.961447,40.693965,-73.871195,40.774297,5
7,44195482,2012-12-11 13:52:00.00000029,2.5,2012-12-11 13:52:00 UTC,0.000000,0.000000,0.000000,0.000000,1
8,15822268,2012-02-17 09:32:00.00000043,9.7,2012-02-17 09:32:00 UTC,-73.975187,40.745767,-74.002720,40.743537,1
9,50611056,2012-03-29 19:06:00.000000273,12.5,2012-03-29 19:06:00 UTC,-74.001065,40.741787,-73.963040,40.775012,1
10,2205147,2015-05-22 17:32:27.0000004,6.5,2015-05-22 17:32:27 UTC,-73.974388,40.746952,-73.988586,40.729805,1
11,6379048,2011-05-23 22:15:00.00000086,8.5,2011-05-23 22:15:00 UTC,0.000000,0.000000,0.000000,0.000000,1
12,31892535,2011-05-17 14:03:00.000000158,3.3,2011-05-17 14:03:00 UTC,-73.966378,40.804440,-73.965890,40.807133,5
13,13012786,2011-06-25 11:19:00.000000102,10.9,2011-06-25 11:19:00 UTC,-73.953352,40.767382,-73.972510,40.796137,1
14,48411337,2010-04-06 22:20:27.0000004,6.9,2010-04-06 22:20:27 UTC,-73.973370,40.755193,-73.978265,40.766375,1
15,46272151,2012-02-21 09:33:00.00000028,9.7,2012-02-21 09:33:00 UTC,-73.990718,40.751920,-73.973053,40.744230,2
16,11875730,2011-09-01 09:21:40.0000002,4.9,2011-09-01 09:21:40 UTC,-73.988908,40.756982,-73.981246,40.760050,1
17,1728270,2011-03-19 23:58:27.0000003,10.5,2011-03-19 23:58:27 UTC,-74.005665,40.741138,-73.977830,40.749338,2
18,49173512,2015-03-25 08:58:35.0000001,12.0,2015-03-25 08:58:35 UTC,-73.962532,40.767189,-73.974457,40.753860,1
19,33157445,2009-08-08 00:20:00.000000183,4.9,2009-08-08 00:20:00 UTC,-73.992075,40.719633,-73.985323,40.727405,1

droping irralevant columns

In [5]:
df.drop(columns=["Unnamed: 0", "key"],inplace=True)

In [6]:
df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5
...,...,...,...,...,...,...,...
199995,3.0,2012-10-28 10:49:00 UTC,-73.987042,40.739367,-73.986525,40.740297,1
199996,7.5,2014-03-14 01:09:00 UTC,-73.984722,40.736837,-74.006672,40.739620,1
199997,30.9,2009-06-29 00:42:00 UTC,-73.986017,40.756487,-73.858957,40.692588,2
199998,14.5,2015-05-20 14:56:25 UTC,-73.997124,40.725452,-73.983215,40.695415,1
199999,14.1,2010-05-15 04:08:00 UTC,-73.984395,40.720077,-73.985508,40.768793,1

In [7]:
df["pickup_datetime"] = pd.to_datetime(df["pickup_datetime"])
df["month"] = df["pickup_datetime"].dt.month
df["day"] = df["pickup_datetime"].dt.day
df["weekday"] = df["pickup_datetime"].dt.weekday
df["year"] = df["pickup_datetime"].dt.year
df["hour"] = df["pickup_datetime"].dt.hour
df.drop(columns=["pickup_datetime"],inplace=True)

In [8]:
df["distance"] = calculate_distance(df["pickup_longitude"], df["pickup_latitude"], df["dropoff_longitude"], df["dropoff_latitude"] )
df.drop(columns=["pickup_longitude"	,"pickup_latitude",	"dropoff_longitude",	"dropoff_latitude"],inplace=True)

In [9]:
df.dropna(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 199999 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   fare_amount      199999 non-null  float64
 1   passenger_count  199999 non-null  int64
 2   month            199999 non-null  int32
 3   day              199999 non-null  int32
 4   weekday          199999 non-null  int32
 5   year             199999 non-null  int32
 6   hour             199999 non-null  int32
 7   distance         199999 non-null  float64
dtypes: float64(2), int32(5), int64(1)
memory usage: 9.9 MB

In [10]:
df.to_csv("cleaned_uber.csv", index= 0)